---
executors:
  sh: &sh
    path: /bin/sh
    options: -c
    quote: true

tasks:

  run: &run
    executor: *sh
    cmd: |
      $WORKSPACE/usr/bin/jk-wrapper
    pre-conditions:
      env:
        WORKSPACE:
      validators:
        - '[ -x $WORKSPACE/usr/bin/jk-wrapper ]'
    on-success:
      executor: *sh
      cmd: |
        stty sane
  r: *run

  build: &build
    executor: *sh
    cmd: |
      : \
      && cmake \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DCMAKE_INSTALL_PREFIX="$WORKSPACE"/usr \
        -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE:-Debug} \
        -S . \
        -B ./build \
        -G Ninja \
      && ninja -C ./build \
      && ninja -C ./build install \
      && :
    pre-conditions:
      env:
        WORKSPACE:
  b: *build

  config: &config
    executor: *sh
    cmd: |
      $EDITOR $WORKSPACE/.jk.yml
    pre-conditions:
      env:
        EDITOR:
        WORKSPACE:
  cfg: *config

  clean: &clean
    executor: *sh
    cmd: |
      : \
      && rm -f *.o *.so *.dylib *.out \
      && rm -rf .clean \
      && rm -rf build \
      && rm -rf .cache \
      && rm -rf *.egg-info \
      && rm -rf usr \
      && :
    pre-conditions:
      validators:
        - '[ $PWD = $WORKSPACE ]'

  test:
    executor: *sh
    cmd: say test 1010
    on-success:
      cmd: say congratz
    on-failure:
      cmd: say l o l
