---
version: '3'

tasks:
  build:
    cmds:
      - echo 'go build -v -i main.go'
    aliases: [b]

  assets:
    cmds:
      - echo 'esbuild --bundle --minify css/index.css > public/bundle.css'
    aliases: [a, ass]

  gen:
    cmds:
      - echo 'gen'
      # - '[ -d .venv ] && rm -rf .venv'
      # - 'python3 -m virtualenv .venv'
      # - .venv/bin/python -m pip install -r requirements.txt
